public class Library {
    /**
     * This java source file was generated by the Gradle 'init' task.
     *
     * @return always true
     */
    public boolean someLibraryMethod() {
        return true;
    }
}
